version: '3.9'
services:
 postgres:
   image: postgres:16
   container_name: postgres_container
   environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: 12345
     POSTGRES_DB: db0
   ports:
     - "5433:5432"
   volumes:
     - ./data:/var/lib/postgresql/data
   restart: always
